### PR TITLE
Test for Lesson 1, Task 1 is not comparable with condition of this Task

### PR DESCRIPTION
**Pull request by fembiba**
Condition of Task mean, values must be more than 100, but in Test we tested with 100 value.

I suggest fix condition of Task to more than or equals 100

https://github.com/Kotlin-Polytech/KotlinAsFirst/blob/35925dfc5c7bf1e566102d67afb546a8e1a37627/src/lesson1/task1/Simple.kt#L98

https://github.com/Kotlin-Polytech/KotlinAsFirst/blob/35925dfc5c7bf1e566102d67afb546a8e1a37627/test/lesson1/task1/Tests.kt#L83

### CODE REVIEW

**Comment by ice-phoenix** [comment]
Hi mate, thanks for noticing this bug in the description! Out of curiosity, why did you decide to use the unconventional order of "равно или больше" instead of a more widely used "больше или равно"?

**Comment by fembiba** [comment]
Hi too! In order to focus on "равно" word. But this is a bad idea. I guess.

**Comment by fembiba** [comment]
Oki. I'm refactored.

**Comment by ice-phoenix** [comment]
Could I ask you to squash the commits in your branch, so that it contains a single commit with the needed changes?

**Comment by fembiba** [comment]
> Could I ask you to squash the commits in your branch, so that it contains a single commit with the needed changes?

Oks. I did it

**Pull request merged**
